"""empty message

Revision ID: 142ab6b233a4
Revises: 
Create Date: 2025-05-27 00:34:39.848288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142ab6b233a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('info_user', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('info_user', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
