"""add id_users_passed

Revision ID: 462dd3ef3757
Revises: 142ab6b233a4
Create Date: 2025-05-27 00:43:31.153607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462dd3ef3757'
down_revision: Union[str, None] = '142ab6b233a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_user', sa.Column('id_users_passed', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_user', 'id_users_passed')
    # ### end Alembic commands ###
