"""Text_total

Revision ID: 6ba7df7417ed
Revises: 21b59dd2c816
Create Date: 2025-05-27 18:39:40.870646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import ARRAY, Text

# revision identifiers, used by Alembic.
revision: str = '6ba7df7417ed'
down_revision: Union[str, None] = '21b59dd2c816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.alter_column(
        'quiz_user',
        'results_users_passed',
        type_=ARRAY(Text),
        postgresql_using='results_users_passed::text[]'
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'quiz_user', 'results_users_passed',
        type_=sa.BigInteger(),
        postgresql_using="results_users_passed::bigint"
    )
    # ### end Alembic commands ###
