"""len_quiz

Revision ID: 79310a597d7f
Revises: c06709fd86e0
Create Date: 2025-06-15 22:57:26.887001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79310a597d7f'
down_revision: Union[str, None] = 'c06709fd86e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Passed_user', sa.Column('len_quiz', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Passed_user', 'len_quiz')
    # ### end Alembic commands ###
