"""quiz_id2

Revision ID: c06709fd86e0
Revises: 92fde873b56b
Create Date: 2025-06-14 10:12:41.716706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06709fd86e0'
down_revision: Union[str, None] = '92fde873b56b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_user', sa.Column('id_quiz', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_user', 'id_quiz')
    # ### end Alembic commands ###
