"""New

Revision ID: c3f3f5c5b4a8
Revises: 6ba7df7417ed
Create Date: 2025-05-27 23:58:14.582573

"""
from typing import Sequence, Union
from sqlalchemy import text
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3f3f5c5b4a8'
down_revision: Union[str, None] = '6ba7df7417ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    # Проверяем, есть ли таблица
    result = conn.execute(text(
        "SELECT to_regclass('public.\"Passed_user\"')"
    )).scalar()
    if not result:
        op.create_table(
            'Passed_user',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('friend_id', sa.BigInteger(), nullable=True),
            sa.Column('user_id', sa.BigInteger(), nullable=True),
            sa.Column('user_name', sa.Text(), nullable=True),
            sa.Column('result_user', sa.BigInteger(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
    conn = op.get_bind()
    exists = conn.execute(text("SELECT to_regclass('public.opros_user')")).scalar()
    if exists:
        op.drop_table('opros_user')
        op.drop_constraint('quiz_user_user_id_fkey', 'quiz_user', type_='foreignkey')
        op.drop_column('quiz_user', 'id_users_passed')
        op.drop_column('quiz_user', 'results_users_passed')
        op.drop_column('quiz_user', 'permission')
        op.drop_column('quiz_user', 'questions_opros')
        op.drop_column('quiz_user', 'name_users_passed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_user', sa.Column('name_users_passed', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('quiz_user', sa.Column('questions_opros', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('quiz_user', sa.Column('permission', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('quiz_user', sa.Column('results_users_passed', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('quiz_user', sa.Column('id_users_passed', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('quiz_user_user_id_fkey', 'quiz_user', 'info_user', ['user_id'], ['user_id'])
    op.create_table('opros_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('opros', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_opros', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['info_user.user_id'], name='opros_user_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='opros_user_pkey')
    )
    op.drop_table('Passed_user')
    # ### end Alembic commands ###
